//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.Web.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class fis_t_data_insrt
    {
        public int FIS_T_DATA_INSRT_ID { get; set; }
        public int FIS_MST_DOC_TYPE_ID { get; set; }
        public int USRINFO_MST_SITE_ID { get; set; }
        public int USRINFO_T_USR_ID { get; set; }
        public string FIS_T_DATA_INSRT_NAME { get; set; }
        public bool FIS_T_DATA_INSRT_IS__ACTIVE { get; set; }
        public string FIS_T_DATA_INSRT_CREATED_BY { get; set; }
        public System.DateTime FIS_T_DATA_INSRT_CREATED_AT { get; set; }
        public string FIS_T_DATA_INSRT_UPDATED_BY { get; set; }
        public System.DateTime FIS_T_DATA_INSRT_UPDATED_AT { get; set; }
        public Nullable<int> FIS_T_DATA_INSRT_FLAG { get; set; }
    }
}
