//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.Web.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class fis_t_data_insrt_detail
    {
        public int FIS_T_DATA_INSRT_DETAIL_ID { get; set; }
        public Nullable<int> FIS_T_DATA_INSRT_ID { get; set; }
        public string FIS_T_DATA_INSRT_DETAIL1 { get; set; }
        public bool FIS_T_DATA_INSRT_DETAIL_IS_ACTIVE { get; set; }
        public string FIS_T_DATA_INSRT_DETAIL_CREATED_BY { get; set; }
        public System.DateTime FIS_T_DATA_INSRT_DETAIL_CREATED_AT { get; set; }
        public string FIS_T_DATA_INSRT_DETAIL_UPDATED_BY { get; set; }
        public System.DateTime FIS_T_DATA_INSRT_DETAIL_UPDATED_AT { get; set; }
    }
}
