//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.Web.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class fis_mst_doc_type
    {
        public int FIS_MST_DOC_TYPE_ID { get; set; }
        public string FIS_MST_DOC_TYPE_NAME { get; set; }
        public string FIS_MST_DOC_TYPE_DETAIL { get; set; }
        public bool FIS_MST_DOC_TYPE_IS_ACTIVE { get; set; }
        public string FIS_MST_DOC_TYPE_CREATED_BY { get; set; }
        public Nullable<int> FIS_MST_DOC_TYPE_CREATED_BY_ID { get; set; }
        public System.DateTime FIS_MST_DOC_TYPE_CREATED_AT { get; set; }
        public string FIS_MST_DOC_TYPE_UPDATED_BY { get; set; }
        public System.DateTime FIS_MST_DOC_TYPE_UPDATED_AT { get; set; }
    }
}
