//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.Web.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class usrinfo_mst_site
    {
        public int USRINFO_MST_SITE_ID { get; set; }
        public string USRINFO_MST_SITE_NAME { get; set; }
        public bool USRINFO_MST_SITE_IS_ACTIVE { get; set; }
        public string USRINFO_MST_SITE_CREATED_BY { get; set; }
        public System.DateTime USRINFO_MST_SITE_CREATED_AT { get; set; }
        public string USRINFO_MST_SITE_UPDATED_BY { get; set; }
        public System.DateTime USRINFO__MST_SITE_UPDATED_AT { get; set; }
    }
}
