//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KM.Web.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class usrinfo_mst_site
    {
        public int USRINFO_MST_SITE_ID { get; set; }
        public string USRINFO_MST_SITE_NAME { get; set; }
        public Nullable<System.DateTime> USRINFO_MST_SITE_DATE { get; set; }
    }
}
